<?php $option_value = $this->getOptionValue(); 
 $value_id = $option_value->getId();
 
/*Settings Manage*/
$settingsFrom = new Xdelivery_Form_Settings();
$settingsFrom->addNav("ads-save-nav", "Save", false);
$settingsFrom->setElementValueById('value_id', $option_value->getId());
$settingModel = (new Xdelivery_Model_Settings())->find(['value_id' => $option_value->getId()]);
if ($settingModel->getId()) {
    $settingData = $settingModel->getData();
    $settingsFrom->populate($settingData);
}else{
   $settingModel =  (new Xdelivery_Model_Settings())->find(['value_id' => $option_value->getId()])->setValueId($option_value->getId())->save();
    $settingData = $settingModel->getData();
    $settingsFrom->populate($settingData);
}

/*Store Manage*/
$storeFrom = new Xdelivery_Form_Store_From();
$storeFrom->addNav("ads-save-nav", "Save", false);
$storeFrom->setElementValueById('value_id', $option_value->getId());
$storeFrom->setElementValueById('commision_percentage', 100);
$storeModel = (new Xdelivery_Model_Store())->find(['value_id' => $option_value->getId()]);
if ($storeModel->getStoreId()) {
    $storeData = $storeModel->getData();
    $storeFrom->populate($storeData);
}
$workingdays = (new Xdelivery_Model_WorkingTimes())::getWorkingDays($storeModel->getStoreId(), $value_id);

/*Payment Method Manage*/
$cashondeliveryFrom = new Xdelivery_Form_PaymentMethod_CashOnDelivery();
$cashondeliveryFrom->addNav("ads-save-nav", "Save", false);
$cashondeliveryFrom->setElementValueById('value_id', $option_value->getId());
$cashondeliveryModel = (new Xdelivery_Model_PaymentMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'cash_on_delivery']);
if ($cashondeliveryModel->getId()) {
    $cashondeliveryData = $cashondeliveryModel->getData();
    $cashondeliveryFrom->populate($cashondeliveryData);
}

/*Payment Method Manage*/
$banktransferFrom = new Xdelivery_Form_PaymentMethod_BankTransfer();
$banktransferFrom->addNav("ads-save-nav", "Save", false);
$banktransferFrom->setElementValueById('value_id', $option_value->getId());
$banktransferModel = (new Xdelivery_Model_PaymentMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'bank_transfer']);
if ($banktransferModel->getId()) {
    $banktransferData = $banktransferModel->getData();
    $banktransferFrom->populate($banktransferData);
}

/*Payment Method Manage*/
$checkmoneyFrom = new Xdelivery_Form_PaymentMethod_CheckMoneyOrder();
$checkmoneyFrom->addNav("ads-save-nav", "Save", false);
$checkmoneyFrom->setElementValueById('value_id', $option_value->getId());
$checkmoneyModel = (new Xdelivery_Model_PaymentMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'check_money_order']);
if ($checkmoneyModel->getId()) {
    $checkmoneyData = $checkmoneyModel->getData();
    $checkmoneyFrom->populate($checkmoneyData);
}

/*Payment Method Manage*/
$ewalletFrom = new Xdelivery_Form_PaymentMethod_Ewallet();
$ewalletFrom->addNav("ads-save-nav", "Save", false);
$ewalletFrom->setElementValueById('value_id', $option_value->getId());
$ewalletModel = (new Xdelivery_Model_PaymentMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'ewallet']);
if ($ewalletModel->getId()) {
    $ewalletData = $ewalletModel->getData();
    $ewalletFrom->populate($ewalletData);
}

/*Payment Method Manage*/
$stripeFrom = new Xdelivery_Form_PaymentMethod_Stripe();
$stripeFrom->addNav("ads-save-nav", "Save", false);
$stripeFrom->setElementValueById('value_id', $option_value->getId());
$stripeModel = (new Xdelivery_Model_PaymentMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'stripe']);
if ($stripeModel->getId()) {
    $stripeData = $stripeModel->getData();
    $stripeFrom->populate($stripeData);
}

/*Payment Method Manage*/
$paypalFrom = new Xdelivery_Form_PaymentMethod_Paypal();
$paypalFrom->addNav("ads-save-nav", "Save", false);
$paypalFrom->setElementValueById('value_id', $option_value->getId());
$paypalModel = (new Xdelivery_Model_PaymentMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'paypal']);
if ($paypalModel->getId()) {
    $paypalData = $paypalModel->getData();
    $paypalFrom->populate($paypalData);
}

/*shipping_methodg Method Manage*/
$freeShippingFrom = new Xdelivery_Form_ShippingMethod_Free();
$freeShippingFrom->addNav("ads-save-nav", "Save", false);
$freeShippingFrom->setElementValueById('value_id', $option_value->getId());
$freeShippingModel = (new Xdelivery_Model_ShippingMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'free']);
if ($freeShippingModel->getId()) {
    $freeShippingData = $freeShippingModel->getData();
    $freeShippingFrom->populate($freeShippingData);
}
 
$flatShippingFrom = new Xdelivery_Form_ShippingMethod_Flat();
$flatShippingFrom->addNav("ads-save-nav", "Save", false);
$flatShippingFrom->setElementValueById('value_id', $option_value->getId());
$FlatShippingModel = (new Xdelivery_Model_ShippingMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'flat']);
if ($FlatShippingModel->getId()) {
    $FlatShippingData = $FlatShippingModel->getData();
    $flatShippingFrom->populate($FlatShippingData);
}

$distanceShippingFrom = new Xdelivery_Form_ShippingMethod_Distance();
$distanceShippingFrom->addNav("ads-save-nav", "Save", false);
$distanceShippingFrom->setElementValueById('value_id', $option_value->getId());
$distanceShippingModel = (new Xdelivery_Model_ShippingMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'distance']);
if ($distanceShippingModel->getId()) {
    $distanceShippingData = $distanceShippingModel->getData();
    $distanceShippingFrom->populate($distanceShippingData);
}
/*
$pincodeShippingFrom = new Xdelivery_Form_ShippingMethod_Pincode();
$pincodeShippingFrom->addNav("ads-save-nav", "Save", false);
$pincodeShippingFrom->setElementValueById('value_id', $option_value->getId());
$pincodeShippingModel = (new Xdelivery_Model_ShippingMethod())->find(['value_id' => $option_value->getId(), 'method_type' => 'pincode']);
if ($pincodeShippingModel->getId()) {
    $settingData = $pincodeShippingModel->getData();
    $pincodeShippingFrom->populate($settingData);
}*/

/*taxes Manage*/
$taxesFrom = new Xdelivery_Form_Tax_From();
$taxesFrom->addNav("ads-save-nav", "Save", false);
$taxesFrom->setElementValueById('value_id', $option_value->getId());
$taxesDeleteFrom = new Xdelivery_Form_Tax_Delete();
$taxes = (new Xdelivery_Model_Tax())->findAll(['value_id' => $value_id , 'status != ?' => 'deleted']);

/*Business day*/
$businessDayFrom = new Xdelivery_Form_BusinessDay();
$businessDayFrom->addNav("ads-save-nav", "Save", false);
$businessDayFrom->setElementValueById('value_id', $option_value->getId());
$businessDayModel = (new Xdelivery_Model_BusinessDay())->find(['value_id' => $option_value->getId()]);
if ($businessDayModel->getId()) {
    $businessDayData = $businessDayModel->getData();
    $businessDayFrom->populate($businessDayData);
}

$parentCategory = (new Xdelivery_Model_Category())->findAll(['value_id' => $value_id, 'parent_id' => 0, 'is_active' => 1 ], 'category_name ASC')->toArray();

$categories = array('0' => 'Home Screen');
foreach ($parentCategory  as $key => $value) {
     $categories[$value['id']] =  $value['category_name'].' Screen' ;
}
 
/*Slider Manage*/
$sliderFrom = new Xdelivery_Form_Slider();
$sliderFrom->form($categories);
$sliderFrom->addNav("ads-save-nav", "Submit", false);
$sliderFrom->setElementValueById('value_id', $option_value->getId());
$sliders = (new Xdelivery_Model_Slider())->findAll(['value_id' => $value_id, 'status != ?' => 'deleted']);
$deleteSliderFrom = new Xdelivery_Form_Slider_Delete();
/*Slider Manage End*/

$foodSettingsFrom = new Xdelivery_Form_FoodSettings();
$foodSettingsFrom->addNav("ads-save-nav", "Save", false);
$foodSettingsFrom->setElementValueById('value_id', $option_value->getId());
if ($settingModel->getId()) {
    $foodSettingsData = $settingModel->getData();
    $foodSettingsFrom->populate($foodSettingsData);
}
 
?>
 
<div id="loadContent">
   <!-- Nav tabs -->
    <ul class="nav nav-tabs parent-tab  recognition_list" role="tablist">
       <?php if($storeModel->getId()) { ?>
        <li  class="active"  role="presentation">
            <a href="#settings" aria-controls="access" role="tab" data-toggle="tab">
               <i class="fa fa-cog" aria-hidden="true"></i>
                <i class="fa fa-spinner fa-spin dynamic-loader hide"></i> 
                <span class="hidden-xs access"><?php echo p__('xdelivery', "Settings") ?></span>
            </a>
        </li>

        <?php if($settingModel->getAppServiceType() == 'food') { ?>
             <li role="presentation">
                <a href="#foodsettings" aria-controls="access" role="tab" data-toggle="tab">
                   <i class="fa fa-cog" aria-hidden="true"></i>
                    <i class="fa fa-spinner fa-spin dynamic-loader hide"></i> 
                    <span class="hidden-xs access"><?php echo p__('xdelivery', "Delivery/Pickup") ?></span>
                </a>
            </li>
        <?php } ?>

        <li role="presentation">
            <a href="#payment_method" aria-controls="options" role="tab" data-toggle="tab">
                <i class="fa fa-credit-card" aria-hidden="true"></i>
                <i class="fa fa-spinner fa-spin dynamic-loader hide"></i>
                <span class="hidden-xs option"><?php echo p__('xdelivery', "Payment Method") ?></span>
            </a>
        </li>

        <li  role="presentation">
            <a href="#shipping_method" aria-controls="options" role="tab" data-toggle="tab">
                <i class="fa fa-truck" aria-hidden="true"></i>
                <span class="hidden-xs option"><?php echo p__('xdelivery', "Shipping Method") ?></span>
            </a>
        </li>

        <li role="presentation">
            <a href="/xdelivery/products/list" target="_blank">
               <i class="fa fa-shopping-bag" aria-hidden="true"></i>
               <span class="hidden-xs option"><?php echo p__('xdelivery', "Products") ?></span>
            </a>
        </li>

        <li role="presentation" >
            <a href="/xdelivery/orders/list" target="_blank" >
               <i class="fa fa-shopping-bag" aria-hidden="true"></i>
               <span class="hidden-xs option"><?php echo p__('xdelivery', "Orders") ?></span>
            </a>
        </li>

        <li role="presentation">
            <a href="#taxes" aria-controls="options" role="tab" data-toggle="tab">
               <i class="fa fa-money" aria-hidden="true"></i>
               <span class="hidden-xs option"><?php echo p__('xdelivery', "Taxes") ?></span>
            </a>
        </li>
       <!--  <li role="presentation">
            <a href="#business_day" aria-controls="options" role="tab" data-toggle="tab" >
               <i class="fa fa-shopping-bag" aria-hidden="true"></i>
               <span class="hidden-xs option"><?php echo p__('xdelivery', "Business Day") ?></span>
            </a>
        </li> -->

         <li role="presentation">
            <a href="#slider" aria-controls="options" role="tab" data-toggle="tab" >
               <i class="fa fa-picture-o" aria-hidden="true"></i>
               <span class="hidden-xs option"><?php echo p__('xdelivery', "Slider") ?></span>
            </a>
        </li>
    
    <?php } ?>
    
    <li role="presentation">
        <?php if($storeModel->getId()) { ?>
            <a href="/xdelivery/store/list" target="_blank">
               <i class="fa fa-map-marker" aria-hidden="true"></i>
               <span class="hidden-xs option"><?php echo p__('xdelivery', "Stores") ?></span>
            </a>            
        <?php }else { ?>
               <a href="#store" aria-controls="options" role="tab" data-toggle="tab" >
                   <i class="fa fa-map-marker" aria-hidden="true"></i>
                   <span class="hidden-xs option"><?php echo p__('xdelivery', "Store") ?></span>
                </a>
        <?php } ?>  
     </li>
    </ul>

    <div class="tab-content">

    	<!-- Layout settings tab -->
        <div role="tabpanel" class="tab-pane <?php echo !empty($storeModel->getStoreId()) ?  'active' : ''; ?>" id="settings">
                <div class="feature-block-list">
	                <h3 class="title-editor no-border-radius title-feature-indent" style="position: relative;"> <?php echo p__('xdelivery', 'Settings'); ?> 
	              	</h3>
                </div>                
                <br>
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $settingsFrom; ?>
                </div>
                <br>
                <!-- Passcode background set -->
	            <div class="section">
	                <?php echo $this->importBackground($option_value, false, false); ?>
	            </div>
        </div>



        <!-- Layout food settings tab -->
        <div role="tabpanel" class="tab-pane" id="foodsettings">
                <div class="feature-block-list">
                    <h3 class="title-editor no-border-radius title-feature-indent" style="position: relative;"> <?php echo p__('xdelivery', 'Delivery/Pickup Settings'); ?> 
                    </h3>
                </div>                
                <br>
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $foodSettingsFrom; ?>
                </div>
        </div>


         <!-- Layout Payment Method tab -->
        <div role="tabpanel" class="tab-pane" id="payment_method">
                <div class="feature-block-list">
                    <h3 class="title-editor no-border-radius title-feature-indent" style="position: relative;"> <?php echo p__('xdelivery', 'Payment Method'); ?> 
                    </h3>
                </div>                
                <br>
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $ewalletFrom; ?>
                </div>
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $cashondeliveryFrom; ?>
                </div>
                 <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $banktransferFrom; ?>
                </div>
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $checkmoneyFrom; ?>
                </div>
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $stripeFrom; ?>
                </div>
                 <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $paypalFrom; ?>
                </div>
 
        </div>

        <!-- Layout Shipping Method tab -->
        <div role="tabpanel" class="tab-pane" id="shipping_method">
                <div class="feature-block-list">
                    <h3 class="title-editor no-border-radius title-feature-indent" style="position: relative;"> <?php echo p__('xdelivery', 'Shipping Method'); ?> 
                    </h3>
                </div>                
                <br>
                
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $freeShippingFrom; ?>
                </div>
               
                 <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $flatShippingFrom; ?>
                </div>

                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $distanceShippingFrom; ?>
                </div>

                <!-- <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $pincodeShippingFrom; ?>
                </div> -->
        </div>

       <!-- Layout Store tab -->
        <div role="tabpanel" class="tab-pane <?php echo empty($storeModel->getId())?  'active' : ''; ?>" id="store">
            <div class="feature-block-list">
                <h3 class="title-editor no-border-radius title-feature-indent" style="position: relative;"> <?php echo p__('xdelivery', 'Store'); ?> 
                </h3>
            </div>                
            <br>
            <div class="container-fluid first-row-feature content-feature feature-manage-items">
                <?php echo $storeFrom; ?>
            </div>
             <?php if($storeModel->getId()) { ?>
             <div class="feature-block-list">
                <div class="margin-top">
                    <h3 class="title-editor no-border-radius title-feature-indent">
                        <?php echo p__('xdelivery', 'Working Day/Time'); ?>
                    </h3>
                    <div class="container-fluid first-row-feature feature-manage-items">
                        <table class="table content-white-bkg sb-pager">
                            <thead>
                            <tr class="border-blue">
                               <th style="width:10%;"><?php echo p__('xdelivery', 'S.NO'); ?></th>
                               <th style="width:15%;"><?php echo p__('xdelivery', 'Days'); ?></th>
                                <th  style="width:15%;"> <?php echo p__('xdelivery', 'Opening'); ?></th>
                                <th  style="width:15%;"> <?php echo p__('xdelivery', 'Closing'); ?></th>
                                <th  style="width:15%;"> <?php echo p__('xdelivery', 'Delivery'); ?></th>
                                <th  style="width:15%;"> <?php echo p__('xdelivery', 'Pickup'); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($workingdays as $key => $working): ?>
                                <tr id="working_manage_element_<?php echo $working->getId(); ?>" class="working-manage-element sb-pager">
                                    <td><?php echo $key+1; ?></td>
                                    <td><?php echo p__('xdelivery', ucfirst($working->getWorkingDay())); ?></td>
                                    <td><?php echo $working->getOpeningTime(); ?></td>
                                    <td><?php echo $working->getClosingTime(); ?></td>
                                    <td><?php echo $working->getEnableDelivery() == 1 ? p__('xdelivery', "Active"): p__('xdelivery', "In Active"); ?></td>
                                    <td><?php echo $working->getEnablePickup()== 1 ? p__('xdelivery', "Active"): p__('xdelivery', "In Active");; ?></td>
                                    <td class="edit-action open-edit text-right" data-id="working_<?php echo $working->getId(); ?>" data-form-url="<?php echo __path("/xdelivery/working/loadform", array("working_id" => $working->getId(), "value_id" => $value_id)); ?>">
                                        <i class="fa fa-pencil"></i>
                                    </td>
                                </tr>
                                <tr class="edit-form" data-id="working_<?php echo $working->getId(); ?>" style="display: none;">
                                      <td colspan="7">
                                          <p class="close-edit" data-id="working_<?php echo $working->getId(); ?>">
                                              <i class="fa fa-times"></i><?php p__('xdelivery', "Close") ?>
                                          </p>
                                      </td>
                                  </tr>
                             <?php endforeach; ?>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        <?php } ?>
        </div>

       <!--business day -->
        <div role="tabpanel" class="tab-pane" id="business_day">
            <div class="feature-block-list">
                <h3 class="title-editor no-border-radius title-feature-indent" style="position: relative;"> <?php echo p__('xdelivery', 'Business Day'); ?> 
                </h3>
            </div>                
            <br>
            <div class="container-fluid first-row-feature content-feature feature-manage-items">
                <?php  echo $businessDayFrom; ?>
            </div>
        </div>

         <!-- slider settings tab -->
        <div role="tabpanel" class="tab-pane" id="slider">
                 <!-- Services block -->
                <div class="feature-block-add margin-top">
                    <h3 class="title-editor no-border-radius title-feature-indent">
                        <?php echo p__('xdelivery', 'Slider'); ?>
                        <button type="button" class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                            <i class="fa fa-plus"></i>
                        </button>
                    </h3>
                </div>

                <div class="feature-block-create margin-top">
                    <h3 class="title-editor no-border-radius title-feature-indent">
                        <?php echo p__('xdelivery', 'Create a New Slider'); ?>
                    </h3>
                    <div class="container-fluid">
                        <?php echo $sliderFrom; ?>
                    </div>
                </div>
                
                <br>
               <?php if($sliders->count() > 0): ?>
                    <div class="feature-block-list">
                        <div class="margin-top">
                            <h3 class="title-editor no-border-radius title-feature-indent">
                                <?php echo p__('xdelivery', 'Manage Slider'); ?>
                                <button type="button" class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </h3>
                            <div class="container-fluid first-row-feature feature-manage-items">
                                <table class="table content-white-bkg sb-pager">
                                    <thead>
                                    <tr class="border-blue">
                                       <th class="sortable" style="width:10%;"><?php echo p__('xdelivery', 'S.NO'); ?></th>
                                       <th class="sortable" style="width:50%;"><?php echo p__('xdelivery', 'Name'); ?></th>
                                        <th  style="width:20%;"> <?php echo p__('xdelivery', 'Status'); ?></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach($sliders as $key => $slider): ?>
                                        <tr id="slider_manage_element_<?php echo $slider->getId(); ?>" class="slider-manage-element sb-pager">
                                            <td><?php echo $key+1; ?></td>
                                            <td><?php echo $slider->getSliderName(); ?></td>
                                            <td><?php echo p__('xdelivery', ucfirst($slider->getStatus())); ?></td>
                                            <td class="edit-action open-edit text-right" data-id="slider_<?php echo $slider->getId(); ?>" data-form-url="<?php echo __path("/xdelivery/slider/loadform", array("slider_id" => $slider->getId(), "value_id" => $value_id)); ?>">
                                                <i class="fa fa-pencil"></i>
                                            </td>

                                            <td class="delete-action">
                                                <?php
                                                    $deleteSliderFrom->setAttrib("data-rowid", "slider_manage_element_".$slider->getId());
                                                    $deleteSliderFrom->getElement("id")->setValue($slider->getId());
                                                   echo $deleteSliderFrom;
                                                ?>
                                           </td>
                                        </tr>
                                        <tr class="edit-form" data-id="slider_<?php echo $slider->getId(); ?>" style="display: none;">
                                              <td colspan="4">
                                                  <p class="close-edit" data-id="store_<?php echo $slider->getId(); ?>">
                                                      <i class="fa fa-times"></i><?php p__('xdelivery', "Close") ?>
                                                  </p>
                                              </td>
                                          </tr>
                                     <?php endforeach; ?>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                <?php endif; ?>
        </div>

       <!-- Layout taxes tab -->
        <div role="tabpanel" class="tab-pane" id="taxes">
                <!-- Services block -->
                <div class="feature-block-add margin-top">
                    <h3 class="title-editor no-border-radius title-feature-indent">
                        <?php echo p__('xdelivery', 'Taxes'); ?>
                        <button type="button" class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                            <i class="fa fa-plus"></i>
                        </button>
                    </h3>
                </div>

                <div class="feature-block-create margin-top">
                    <h3 class="title-editor no-border-radius title-feature-indent">
                        <?php echo p__('xdelivery', 'Create a New Tax'); ?>
                    </h3>
                    <div class="container-fluid first-row-feature content-feature feature-manage-items margin-top">
                        <?php echo $taxesFrom; ?>
                    </div>
                </div>
                
                <br>
               <?php if($taxes->count() > 0): ?>
                    <div class="feature-block-list">
                        <div class="margin-top">
                            <h3 class="title-editor no-border-radius title-feature-indent">
                                <?php echo p__('xdelivery', 'Manage Taxes'); ?>
                                <button type="button" class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </h3>
                            <div class="container-fluid first-row-feature feature-manage-items">
                                <table class="table content-white-bkg sb-pager">
                                    <thead>
                                    <tr class="border-blue">
                                       <th class="sortable" style="width:10%;"><?php echo p__('xdelivery', 'S.NO'); ?></th>
                                        <th class="sortable" style="width:50%;"><?php echo p__('xdelivery', 'Name'); ?></th>
                                        <th  style="width:20%;"><?php echo p__('xdelivery', 'Rate'); ?></th>
                                        <th></th>
                                         <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach($taxes as $key => $tax): ?>
                                        <tr id="store_manage_element_<?php echo $tax->getId(); ?>" class="store-manage-element sb-pager">
                                            <td><?php echo $key+1; ?></td>
                                            <td><?php echo $tax->getName(); ?></td>
                                             <td><?php echo $tax->getTaxRate(); ?>%</td>
                                             <td class="edit-action open-edit text-right" data-id="taxes_<?php echo $tax->getId(); ?>" data-form-url="<?php echo __path("/xdelivery/settings/loadtaxform", array("id" => $tax->getId(), "value_id" => $value_id)); ?>">
                                                <i class="fa fa-pencil"></i>
                                            </td>

                                            <td class="delete-action">
                                                <?php
                                                    $taxesDeleteFrom->setAttrib("data-rowid", "store_manage_element_".$tax->getId());
                                                    $taxesDeleteFrom->getElement("id")->setValue($tax->getId());
                                                   echo $taxesDeleteFrom;
                                                ?>
                                           </td>
                                        </tr>
                                        <tr class="edit-form" data-id="taxes_<?php echo $tax->getId(); ?>" style="display: none;">
                                              <td colspan="5">
                                                  <p class="close-edit" data-id="taxes_<?php echo $tax->getId(); ?>">
                                                      <i class="fa fa-times"></i><?php echo p__('xdelivery', "Close") ?>
                                                  </p>
                                              </td>
                                          </tr>
                                     <?php endforeach; ?>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                <?php endif; ?>
        </div>


    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        bindForms("#loadContent");

        function appType(){
            if($("#app_service_type").val() == 'other'){
                $("#home_screen option[value='store']").hide();
                $("#home_screen option[value='product']").show();
                $("#home_screen option[value='category']").show();
               $("#home_screen").children("option[value='category']").prop('selected',true);
            }else{
                $("#home_screen option[value='store']").show();
                $("#home_screen option[value='product']").hide();
                $("#home_screen option[value='category']").hide();
                $("#home_screen").children("option[value='store']").prop('selected',true);
            }   
        }

        setTimeout(function(){
            appType();
        },300);

        $(document).on("change", '#app_service_type', function(){
            appType();
        });

        setTimeout(function(){
            if ($('.select_payment_paypal').val() == 'live') {
                formlivecondition();
            } else {
                formsandboxcondition();
            }
        },3000);

        function formlivecondition(){
            $('#sandboxusername').parent().parent().hide();
            $('#sandboxpassword').parent().parent().hide();
            $('#sandboxsignature').parent().parent().hide();
            $('#username').parent().parent().show();
            $('#password').parent().parent().show();
            $('#signature').parent().parent().show();
        }

        function formsandboxcondition(){
            $('#sandboxusername').parent().parent().show();
            $('#sandboxpassword').parent().parent().show();
            $('#sandboxsignature').parent().parent().show();
            $('#username').parent().parent().hide();
            $('#password').parent().parent().hide();
            $('#signature').parent().parent().hide();
        }

        $(document).on("change", '.select_payment_paypal', function(){
            if (this.value == 'live') {
                formlivecondition();
            } else {
                formsandboxcondition();
            }
        });
   });
</script>

    <!-- Map Start  -->
<?php 
 $googlemaps_key =  $this->getApplication()->getGooglemapsKey();
 ?>
 <script type="text/javascript">     
  function initMap(){
        var autocomplete = new google.maps.places.Autocomplete($("#store_location")[0], {});
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
             var near_place = autocomplete.getPlace();
             document.getElementById('address_lat').value = near_place.geometry.location.lat();
             document.getElementById('address_lng').value = near_place.geometry.location.lng();
        });
    }
 </script>
 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&key=<?php echo $googlemaps_key;?>&libraries=places&callback=initMap"></script>    
<!-- Map end  -->
